version: "0.1"
environments:
  - name: develop
    branch: develop
    mode: pull-request
apps:
  - name: test_ci_cd
    path: src/
    text-resources:
      - path: "*.vue"
        format: vue-hardcoded
text-resources:
  - path: custom/lng/*.json
    format: nested-key-value
