name: CI
on:
  push:
    branches:
      - develop #here we choose to deploy only when a push is detected on the develop branch
jobs:
  check:
    name: Check files
    outputs:
      deploy_admin: ${{ steps.check_files.outputs.deploy_admin }}
      deploy_front: ${{ steps.check_files.outputs.deploy_front }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          echo "deploy_admin=false" >> $GITHUB_OUTPUT
          echo "deploy_front=false" >> $GITHUB_OUTPUT

          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != admin/* ]]; then
              echo "This modified file is not under the admin folder. so we need to deploy front"
              echo "deploy_front=true" >> $GITHUB_OUTPUT
            else
              echo "This modified file is not under the admin folder. so we need to deploy front"
              echo "deploy_admin=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt
  build_front:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - env:
          DEPLOY_FRONT: ${{needs.check.outputs.deploy_front}}
        run: echo "should deploy front $DEPLOY_FRONT"
  build_admin:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - env:
          DEPLOY_ADMIN: ${{needs.check.outputs.deploy_admin}}
        run: echo "should deploy admin $DEPLOY_ADMIN"
